# Generated by Django 4.2.6 on 2024-01-29 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='com',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 29, 23, 46, 53, 757815)),
        ),
        migrations.AlterField(
            model_name='com',
            name='image',
            field=models.ImageField(blank=True, default='upload/1896615.jpg', null=True, upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 29, 23, 46, 53, 758079)),
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 29, 23, 46, 53, 758239)),
        ),
    ]
